### ISSUE TITLE
Need scripts for Figure 4 in paper

### ISSUE THREAD

**Issue by fantasy520** [snu-comparch/InfiniGen#2]
Hello, great work, very impressive. I would now like to reproduce the optimal results in Figure 4 of the paper, do you plan to open source this part of the code?

**Comment by leewonbeom** [comment]
Hi @fantasy520,
Thank you for your kind words. We are glad that you found it impressive.

Currently, we don't have plans to open-source the code for Figure 4 or other figures in the Motivation section.

However, I'm happy to provide some details about the experiment, especially for the Optimal case, to help you reproduce the results:

1. We collect the attention scores (i.e., the result of the query and key matrix multiplication) from the OPT-6.7B model with an input length of 2000 tokens across the layers (i.e., 2000 x 2000 attention score matrix for each head and layer).

2. For each row of the attention score matrix, we retain only the 200 elements with the highest attention scores and mask out the other elements (e.g., setting the values to a large negative number). 
 
3. We apply the softmax operation to both the original attention score and masked attention score. 

4. We measure the cosine similarity using the attention weights (i.e., attention score after softmax operation). 

The graph presents the average cosine similarity across the heads of each layer.
Let me know if you have further questions!

**Comment by fantasy520** [comment]
Thank you for the details, I think I can modify and reproduce based on your reply
